/**
 * MEDORCOIN PRODUCTION API SERVER
 * Role: State Observer & Auth Gateway (Read-Only Consensus)
 */

const express = require("express");
const bodyParser = require("body-parser");
const http = require("http");
const path = require("path");
require("dotenv").config();

const TransactionEngine = require('./transaction_engine.cjs');
const AuthService = require('./auth_service.cjs');

// Initialize Engine (Connects to the persistent state generated by the Master)
const engine = new TransactionEngine({ nodeId: "medor-api-gateway" });
const authService = new AuthService(engine);

let addon;
try {
  addon = require(path.join(__dirname, "build", "Release", "medorcoin_addon.node"));
} catch (e) {
  addon = null; 
}

const app = express();
const server = http.createServer(app);
const PORT = process.env.PORT || 5000;

app.use(bodyParser.json());

/**
 * OBSERVATION LAYER
 * Reads the consensus state generated by the Ultimate Master.
 */
async function getConsensusState() {
    try {
        // Master writes 'network:stats' when blocks are confirmed or difficulty adjusts
        const stats = await engine.db.get('network:stats').catch(() => ({}));
        return {
            height: Number(engine.currentHeight) || 0,
            lastHash: String(engine.lastBlockHash || "0".repeat(64)),
            difficulty: stats.difficulty || "6",
            // Monitoring flag derived from Master's anomaly detection
            fallbackActive: !!stats.fallbackAlert 
        };
    } catch (e) {
        return { height: 0, lastHash: "0".repeat(64), difficulty: "6", fallbackActive: false };
    }
}

// --- AUTHENTICATION ROUTES ---

app.post('/api/signup', async (req, res) => {
    try {
        const { username, password } = req.body;
        const user = await authService.signup(username, password);
        res.json({ success: true, address: user.address, mnemonic: user.mnemonic });
    } catch (e) { 
        res.status(400).json({ success: false, error: e.message }); 
    }
});

app.post('/api/login', async (req, res) => {
    try {
        const { username, password } = req.body;
        const session = await authService.login(username, password);
        res.json({ success: true, token: session.token, address: session.address });
    } catch (e) {
        res.status(401).json({ success: false, error: "Authentication failed" });
    }
});

// --- USER & NETWORK STATE ---

app.get('/api/user-stats', async (req, res) => {
    try {
        const { addr, token } = req.query;
        if (!addr || !token) return res.status(400).json({ error: "Missing parameters" });

        // Verify session against Master's session store
        const sessionAddr = await engine.db.get(`session:${token}`).catch(() => null);
        if (!sessionAddr || sessionAddr !== addr) {
            return res.status(401).json({ error: "Unauthorized" });
        }

        // Fetch user balance from Master's state partition
        const state = await engine.db.get(`${engine.PARTITIONS.STATE}${addr}`).catch(() => ({ balance: "0" }));
        const consensus = await getConsensusState();

        res.json({
            success: true,
            balance: (BigInt(state.balance || 0) / 100000000n).toString(),
            speed: 4.5,
            network: consensus
        });
    } catch (e) {
        res.status(500).json({ error: "Internal State Error" });
    }
});

// --- CORE GATEWAY ROUTES ---

app.get("/health", async (req, res) => {
    const consensus = await getConsensusState();
    res.json({ 
        status: "ok", 
        height: consensus.height, 
        core_ready: !!addon,
        anomaly_detected: consensus.fallbackActive 
    });
});

app.post("/tx", (req, res) => {
    if (!addon) return res.status(503).json({ error: "Core Addon Unavailable" });
    // Submission is handled by the Addon's high-speed Mempool
    const success = addon.submitTransaction(req.body);
    res.json({ success });
});

// --- INITIALIZATION ---
server.listen(PORT, async () => {
  // Recover engine state to ensure Height and BlockHash are synced
  await engine.recoverFromCrash().catch(() => {});
  console.log(`[MEDOR-API] Observer active on port ${PORT}`);
});
